/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/v1/articles": {
    get: operations["getArticles"];
    post: operations["write"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    WriteRequestBody: {
      title?: string;
      body?: string;
    };
    Article: {
      /** Format: int64 */
      id?: number;
      title?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  getArticles: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["Article"][];
        };
      };
    };
  };
  write: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["WriteRequestBody"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": {
            [key: string]: Record<string, never>;
          };
        };
      };
    };
  };
}
